### ISSUE TITLE
'opdns_libssl' not found when compiling on Debian

### ISSUE THREAD

**Issue by dvergeylen** [Netfuture/tlsinterposer#17]
Hello,

Thank you for the implementation of tls interposer.

I am having trouble when compiling with debian, tried 2.6.32-042stab103.6 (stable) and 3.12.9-1+rpi3 (raspbian). In both cases I have the same error.

It seems "opdns_libssl" is not declared, and a grep on the entire source doesn't find it twice neither. Maybe should it be deduced from DEFAULT_SSLLIB? ldconfig parsing works fine in the Makefile.

> git clone https://github.com/Netfuture/tlsinterposer.git
> Cloning into 'tlsinterposer'...
> remote: Counting objects: 243, done.
> remote: Total 243 (delta 0), reused 0 (delta 0), pack-reused 243
> Receiving objects: 100% (243/243), 307.49 KiB | 514 KiB/s, done.
> Resolving deltas: 100% (129/129), done.
> p2b@vps69779:~/divers$ cd tlsinterposer/
> p2b@vps69779:~/divers/tlsinterposer$ make
> ldconfig -p | sed -n -e 's/^\t*\(libssl\.so\.[0-9.]*\).*/#define DEFAULT_SSLLIB "\1"/p' > ssl-version.h
> cc -g -Wall -O2 -fPIC -shared -o libtlsinterposer.so tlsinterposer.c -ldl
> tlsinterposer.c: In function ‘interposer_parse_opts’:
> tlsinterposer.c:187:32: error: ‘opdns_libssl’ undeclared (first use in this function)
> tlsinterposer.c:187:32: note: each undeclared identifier is reported only once for each function it appears in
> make: *** [libtlsinterposer.so] Erreur 1

Have a nice day and again, thank you for the job done!

Daniel.

**Comment by MarcelWaldvogel** [comment]
[opDNS](https://netfuture.ch/2014/12/boost-dns-privacy-reliability-and-efficiency-with-opdns-safe-query-elimination/) is based in part on TLS interposer. I only partially fed back some of the improvements I did there. 71115ac678ebf1b85f07f2afa46853b0c83a6ee2 fixes this. Oops!

**Comment by dvergeylen** [comment]
Tested and it works, Thank you!
